spring:
  application:
    name: oasis25-backend
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  forward-headers-strategy: framework

oasis:
  cors:
    allowed-origins: https://oasis25.duckdns.org,http://localhost:3000,http://localhost:5173,http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

imgbb:
  api-key: ${IMGBB_API_KEY:79434fae55cd7419b62afd8ea3885a74}
