spring:
  application:
    name: oasis25-backend
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

imgbb:
  api-key: ${IMGBB_API_KEY:79434fae55cd7419b62afd8ea3885a74}
